#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Removing up raspberry repositories"
source "$(dirname $0)/../build_common"


if [ -f /tmp/build/debian.sources ]; then
mv -vf /tmp/build/debian.sources /etc/apt/sources.list.d/debian.sources 
fi

# only remove the repository if we added it
if [ -f /tmp/build/rpi_sources.list ]; then
for repo in "$(cat /tmp/build/rpi_sources.list)"
do
add-apt-repository -r -y "${repo}"
done
fi

# restore sources.list
cp -vf /tmp/build/sources.list /etc/apt/sources.list

apt update
