#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Removing up raspberry repositories"
source "$(dirname $0)/../build_common"


rm -vf /etc/apt/sources.list.d/raspi.sources
rm -vf /etc/apt/preferences.d/rpi

apt update
