#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT
set -x
STEP_DESCRIPTION="Setting up raspberry repositories"
source "$(dirname $0)/../build_common"

# Add raspberry pi sources
cat > /etc/apt/sources.list.d/raspi.sources << EOF
Types: deb-src
URIs: http://archive.raspberrypi.com/debian/
Suites: ${DEBOOTSTRAP_TARGET}
Components: main
Architectures: ${RPI_APT_ARCH}
Signed-By: /usr/share/keyrings/raspberrypi-archive-keyring.pgp
EOF


curl -4 -fSL --connect-timeout 5 --max-time 20 --retry 8 --retry-all-errors --retry-delay 1 https://archive.raspberrypi.com/debian/raspberrypi.gpg.key -o /usr/share/keyrings/raspberrypi-archive-keyring.pgp

# sanity check the keys received
gpg --show-keys /usr/share/keyrings/raspberrypi-archive-keyring.pgp

# Add high priority
cat > /etc/apt/preferences.d/rpi << EOF
Package: *
Pin: release o=Raspberry Pi Foundation
Pin-Priority: 1001
EOF



# setup multiarch by adding current arch to sources list
# sed -ri "s/^deb (\w+)/deb [arch=$(dpkg --print-architecture)] \1/g" /etc/apt/sources.list

apt_update
