#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT
set -x
STEP_DESCRIPTION="Setting up raspberry repositories"
source "$(dirname $0)/../build_common"


# create backup of sources.list 
if [ -f /etc/apt/sources.list ]; then
    cp -vf /etc/apt/sources.list /tmp/build/sources.list
else
    touch /tmp/build/sources.list
fi

for key in ${RPI_APT_KEYS[@]}
do
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ${key}
done


# only add the repository if it does not exist
# otherwise it will cause package download failures
for repo in "${RPI_APT_SOURCES[@]}"
do
REPO_URL=$(echo "${repo}" | cut -d' ' -f3)
REPO_URL=${REPO_URL%/}
if apt policy | grep $REPO_URL ; then
    echo "Repository $REPO_URL already exists"
else 
    echo "Adding repository $REPO_URL"
    add-apt-repository  -s -y "${repo}"
    echo "${repo}" >> /tmp/build/rpi_sources.list
    echo "${repo}" | sed -r 's/^deb /deb-src /g' >> /etc/apt/sources.list
fi
done



# setup multiarch by adding current arch to sources list
# sed -ri "s/^deb (\w+)/deb [arch=$(dpkg --print-architecture)] \1/g" /etc/apt/sources.list

apt update
