#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT
set -x
STEP_DESCRIPTION="Setting up raspberry repositories"
source "$(dirname $0)/../build_common"


# create backup of sources.list 
if [ -f /etc/apt/sources.list ]; then
    cp -vf /etc/apt/sources.list /tmp/build/sources.list
else
    touch /tmp/build/sources.list
fi

for key in ${RPI_APT_KEYS[@]}
do
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ${key}
done

if [ -f /etc/apt/sources.list.d/debian.sources ]; then
mv -vf /etc/apt/sources.list.d/debian.sources /tmp/build/debian.sources
apt update 
fi


rm -vf /etc/apt/sources.list

# only add the repository if it does not exist
# otherwise it will cause package download failures
for repo in "${RPI_APT_SOURCES[@]}"
do
REPO_URL=$(echo "${repo}" | cut -d' ' -f3)
REPO_URL=${REPO_URL%/}
echo "Adding repository $REPO_URL"
echo "${repo}" >> /etc/apt/sources.list
echo "${repo}" | sed -r 's/^deb /deb-src /g' >> /etc/apt/sources.list
done

# Add high priority
cat << EOF >> /etc/apt/preferences.d/rpi
Package: *
Pin: release o=Raspberry Pi Foundation
Pin-Priority: 1001
EOF



# setup multiarch by adding current arch to sources list
# sed -ri "s/^deb (\w+)/deb [arch=$(dpkg --print-architecture)] \1/g" /etc/apt/sources.list

apt update
