#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Binutils"
source "$(dirname $0)/../build_common"

BINUTILS_CONFIGURATION_OPTIONS="$BINUTILS_CONFIGURATION_OPTIONS --disable-multilib" 

mkdir -p build-binutils
cd build-binutils
set -x
../binutils-$BINUTILS_VERSION/configure --prefix=$INSTALL_PATH --target=$TARGET $BINUTILS_CONFIGURATION_OPTIONS
set +x
make $PARALLEL_MAKE all
make install
cd ..