#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Standard C Library & the rest of Glibc"
source "$(dirname $0)/../build_common"

cd build-glibc
make $PARALLEL_MAKE all $GLIBC_MAKE_FLAGS
make install
cd ..