FROM debian:bullseye-slim

ARG BUILD_UID=499
ARG BUILD_GID=499
ARG KEEP_BUILD_ARTIFACTS=FALSE
ARG SKU_DIR=NON_EXISTENT_FILE
ARG BUILD_ARCH=armhf

RUN apt update && apt install -y wget

RUN groupadd -g $BUILD_GID crossbuilder
RUN useradd -d /home/crossbuilder -m -g $BUILD_GID -u $BUILD_UID -s /bin/bash crossbuilder
COPY --chown=crossbuilder:crossbuilder ./build_tools /home/crossbuilder/build_tools
COPY --chown=crossbuilder:crossbuilder ./scripts /home/crossbuilder/scripts
COPY --chown=crossbuilder:crossbuilder $SKU_DIR /home/crossbuilder/sku
RUN touch /home/crossbuilder/sku.$(basename $SKU_DIR)

# Non-interactive configuration of tzdata
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true
RUN { echo 'tzdata tzdata/Areas select Etc'; echo 'tzdata tzdata/Zones/Etc select UTC'; } | debconf-set-selections

RUN /bin/bash  -o pipefail -c " KEEP_BUILD_ARTIFACTS=$KEEP_BUILD_ARTIFACTS /home/crossbuilder/scripts/build_cross_tools_armhf /home/crossbuilder/sku -j 2>&1 | tee /tmp/build.log"

CMD ["/bin/bash"]