ARG BASE_IMAGE_REPO=effectiverange/armhf-tools-base
ARG BASE_IMAGE_VER=latest

FROM ${BASE_IMAGE_REPO}:${BASE_IMAGE_VER}

ARG DEVC_ARCH=$DEVC_ARCH

RUN apt update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt upgrade -y && \
    apt install -y gcc wget cmake python3 python3-pip inetutils-ping openssh-client pkg-config dpkg-dev nano git sudo


# Set up start script
COPY --chown=crossbuilder:crossbuilder ./scripts/devc/start.sh /home/crossbuilder/start.sh
WORKDIR "/home/crossbuilder"

CMD ["/home/crossbuilder/start.sh"]
