#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Applying patches"
source "$(dirname $0)/../build_common"

if [ -d "$SKU_PATCH_DIR" ]
then
    for pf in $(ls -1 "$SKU_PATCH_DIR" | sort )
    do
        patch_file=$(readlink -f "$SKU_PATCH_DIR/$pf")
        to_patch="$(echo $patch_file | sed -r 's|.*/[0-9]+-(\w+)\.patch|\1|')"
        patch_dir=$(find . -maxdepth  1 -name $to_patch\* -type d)
        pushd $patch_dir
        echo "Applying in $PWD : $patch_file ..."
        patch -u -N --verbose -p0 -s -i $patch_file || true
        popd
    done
fi