#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="C/C++ Compilers"
source "$(dirname $0)/../build_common"

mkdir -p build-gcc
cd build-gcc


# NOTE: setting here build, or host causes carnage, everything will fail
set -x
../$GCC_WITH_VER/configure --host=$MACHTYPE --target=$TARGET $GCC_CONFIGURATION_OPTIONS 
set +x
make $PARALLEL_MAKE all-gcc
make install-gcc
cd ..

if [ -n "$GCC_SUFFIX" ]
then
 for f in  $(find "$INSTALL_PATH/bin/" -name "$TARGET-*$GCC_SUFFIX")
 do
   ln -v -r -s -f "$f" ${f%"$GCC_SUFFIX"}
 done
fi