#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Standard C Library Headers and Startup Files"
source "$(dirname $0)/../build_common"

mkdir -p build-glibc
cd build-glibc
# TODO: figure out matching glibc options somehow
set -x 
../glibc-$GLIBC_VERSION/configure --prefix=$INSTALL_PATH/$TARGET --build=$MACHTYPE --host=$TARGET --target=$TARGET --with-headers=$INSTALL_PATH/$TARGET/include $GLIBC_CONFIGURATION_OPTIONS libc_cv_forced_unwind=yes    
set +x
make install-bootstrap-headers=yes install-headers
make $PARALLEL_MAKE csu/subdir_lib
install csu/crt1.o csu/crti.o csu/crtn.o "$INSTALL_PATH/$TARGET/lib/"
$TARGET-gcc -nostdlib -nostartfiles -shared -x c /dev/null -o "$INSTALL_PATH/$TARGET/lib/libc.so"
touch $INSTALL_PATH/$TARGET/include/gnu/stubs.h
cd ..
