#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Standard C++ Library & the rest of GCC"
source "$(dirname $0)/../build_common"

cd build-gcc
make $PARALLEL_MAKE all
make install
cd ..