#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT
STEP_DESCRIPTION="Building kernel scripts for module cross compilation"
source "$(dirname $0)/../build_common"

pushd "${LINUX_SRC_PATH}"

cp -fv "${SKU_DIR}"/.config ./

# invoking first to compile tools if any
make ARCH=$LINUX_ARCH CROSS_COMPILE=$TARGET- listnewconfig

LINUX_NEW_CONFIG="$(make ARCH=$LINUX_ARCH CROSS_COMPILE=$TARGET- listnewconfig)"
if [ -n "$LINUX_NEW_CONFIG" ]
then
  echo "Linux kernel config error, there are new configs:"
  echo "${LINUX_NEW_CONFIG}"
  exit
fi

make ARCH=$LINUX_ARCH CROSS_COMPILE=$TARGET- scripts
make ARCH=$LINUX_ARCH CROSS_COMPILE=$TARGET- scripts/module.lds

cat > /usr/bin/xkmake <<EOF
#!/bin/bash
exec make ARCH="${LINUX_ARCH}" CROSS_COMPILE="${TARGET}-" "\$@"
EOF
chmod 755 /usr/bin/xkmake

popd