#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

set -e

STEP_DESCRIPTION="creating cross cmake toolchain file and wrapper"
source "$(dirname $0)/../build_common"

echo "CMAKE_GENERATOR=Ninja" >> /etc/environment

ln -s -f -v $(which cmake) /usr/bin/xcmake
