#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

# TODO: parametrize in the STAGING directory
cat > /usr/share/cmake/toolchain.cmake  << EOF
set(CMAKE_SYSROOT "/var/chroot/buildroot")
set(CMAKE_VERBOSE_MAKEFILE ON)
SET(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
set(CMAKE_INSTALL_PREFIX \${CMAKE_SYSROOT} CACHE PATH "..." FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE amd64)

set(PKG_CONFIG_EXECUTABLE xpkg-config)

EOF

echo "CMAKE_TOOLCHAIN_FILE=/usr/share/cmake/toolchain.cmake" >> /etc/environment
echo "CMAKE_GENERATOR=Ninja" >> /etc/environment

cat > /usr/bin/xcmake << EOF
#!/bin/bash

cmake --toolchain /usr/share/cmake/toolchain.cmake --install-prefix /var/chroot/buildroot "\$@"

EOF

chmod 755 /usr/bin/xcmake