#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

set -e

STEP_DESCRIPTION="debootstrapping build sysroot"
source "$(dirname $0)/../build_common"

mkdir -p /var/chroot/buildroot
RELEASE=$(lsb_release -c | awk '{print $2}')

debootstrap --variant=buildd --components=main,universe $RELEASE  /var/chroot/buildroot
