#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

set -x
STEP_DESCRIPTION="Install build utils into schroot"
source "$(dirname $0)/../build_common"

# Install necessary packages
# Fix blocking netbase install
apt install -y --no-install-recommends -o Dpkg::Options::="--force-confnew" netbase

apt install -y --no-install-recommends ninja-build git debhelper devscripts equivs

# Install packages for python development
apt install -y --no-install-recommends python3 python3-pip python3-dev python3-wheel python3-venv python3-virtualenv python3-all

# Install python build tool packages
apt install -y --no-install-recommends python3-stdeb python3-setuptools python3-setuptools-scm dh-virtualenv dh-python
gem install fpm

# Bootstrap pipx with pipx
python3 -m venv /tmp/bootstrap_pipx
/tmp/bootstrap_pipx/bin/pip install pipx
PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin /tmp/bootstrap_pipx/bin/pipx install --global pipx
rm -rf /tmp/bootstrap_pipx

# Install python build packages
pipx install --global ninja
pipx install --global patchelf 
pipx install --global meson
