#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT
set -x
STEP_DESCRIPTION="Install build utils into schroot"
source "$(dirname $0)/../build_common"

# Install necessary packages
# Fix blocking netbase install
apt install -y --no-install-recommends -o Dpkg::Options::="--force-confnew" netbase

apt install -y --no-install-recommends ninja-build git debhelper devscripts equivs dbus

# Install packages for python development
apt install -y --no-install-recommends python3 python3-pip python3-dev python3-wheel python3-stdeb python3-venv python3-virtualenv dh-virtualenv dh-python python3-all

# Install library dev packages
apt install -y --no-install-recommends libsystemd-dev libdbus-glib-1-dev libgirepository1.0-dev libcairo2-dev

# Bootstrap pipx with pipx
python3 -m venv /tmp/bootstrap_pipx
/tmp/bootstrap_pipx/bin/pip install pipx
PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin /tmp/bootstrap_pipx/bin/pipx install --global pipx
rm -rf /tmp/bootstrap_pipx

# Install python build packages
pipx install --global ninja
pipx install --global patchelf 
pipx install --global meson