#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Install build utils into schroot"
source "$(dirname $0)/../build_common"

# Install necessary packages
# Fix blocking netbase install
apt install -y --no-install-recommends -o Dpkg::Options::="--force-confnew" netbase

apt install -y --no-install-recommends ninja-build git debhelper devscripts equivs dbus

# Install packages for python development
apt install -y --no-install-recommends python3 python3-pip python3-dev python3-virtualenv dh-virtualenv dh-python python3-all

# Install library dev packages
apt install -y --no-install-recommends libsystemd-dev libdbus-glib-1-dev libgirepository1.0-dev libcairo2-dev

chroot /var/chroot/buildroot pip install stdeb

# Install python build packages
# NOTE: https://github.com/scikit-build/ninja-python-distributions/issues/226 latest ninja fails to build
pip3 install wheel ninja==1.10.2.3 patchelf meson
