#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Add ldconfig entry for pointing to schroot"
source "$(dirname $0)/../build_common"

echo "/var/chroot/buildroot/usr/lib/x86_64-linux-gnu" > /etc/ld.so.conf.d/schroot-x86_64-linux-gnu.conf
