#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Setup gdb pretty printers"
source "$(dirname $0)/../build_common"

mkdir -p /usr/share/gdb/auto-load/var/chroot/buildroot
cd /usr/share/gdb/auto-load/var/chroot/buildroot
ln -s ../../../lib ./lib
ln -s ../../../usr ./usr
