#!/bin/bash
set -x
# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Debootstrap buildroot"
source "$(dirname $0)/../build_common"

set -o pipefail
mkdir -p /var/chroot/
rm -rf /var/chroot/buildroot
debootstrap --arch=${RPI_APT_ARCH} --verbose --foreign --include=libc-bin,dash --variant=buildd ${DEBOOTSTRAP_TARGET} /var/chroot/buildroot http://deb.debian.org/debian
if chroot /var/chroot/buildroot /debootstrap/debootstrap --second-stage ; then
    ehco "Debootstrap succeeded"
else
    echo "Debootstrap failed"
    cat /var/chroot/buildroot/debootstrap/debootstrap.log || true
    cat /debootstrap/debootstrap.log || true
fi
