#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

set -e
{ echo 'tzdata tzdata/Areas select Etc'; echo 'tzdata tzdata/Zones/Etc select UTC'; } | debconf-set-selections

ROOT_DIR="$(dirname $0)"

HOST_ARCH=$(dpkg --print-architecture)
BUILD_ARCH=$1
shift 1

. "$ROOT_DIR/packages"

if [ -e "$ROOT_DIR/packages_$BUILD_ARCH" ]
then
. "$ROOT_DIR/packages_$BUILD_ARCH"
fi

apt-get update && apt-get upgrade -y

apt-get install -y --no-install-recommends $PACKAGES_TO_INSTALL


# Install latest clang tooling
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
wget -O - https://apt.llvm.org/llvm.sh > /tmp/llvm.sh 
chmod +x /tmp/llvm.sh 

# In native devc install all clang and llvm packages
if [ $HOST_ARCH == $BUILD_ARCH ];then
 /tmp/llvm.sh all
else
 /tmp/llvm.sh
fi
CLANGD_EXE=$(ls -1 /usr/bin/clangd-* | sort -hr | head -n1)
LLVM_VERSION=$(echo $CLANGD_EXE | cut -d- -f2)
apt-get install -y --no-install-recommends clang-format-$LLVM_VERSION
# Add in unversioned symlinks for clangd and clang-format
ln -sfv $CLANGD_EXE /usr/bin/clangd
ln -sfv /usr/bin/clang-format-$LLVM_VERSION /usr/bin/clang-format
ln -sfv /usr/bin/clang-format-diff-$LLVM_VERSION /usr/bin/clang-format-diff


# Install latest stable CMake 
wget -O - https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-linux-x86_64.sh > /tmp/cmake_install.sh
/bin/bash /tmp/cmake_install.sh --skip-license  --prefix=/usr

# Installing latest packaging tools
mkdir -p /opt
cd /opt
git clone --depth=1 -b latest  https://github.com/EffectiveRange/packaging-tools
for packscript in $(find /opt/packaging-tools/ -name pack_\*)
do
packname=$(basename "$packscript")
ln -svf "$packscript" "/usr/local/bin/$packname"
done

mkdir -p /tmp/build

cd /tmp/build 

for step in $( ls -1 "$ROOT_DIR/build_steps_$BUILD_ARCH/" | sort -n ) 
do
/bin/bash "$ROOT_DIR/build_steps_$BUILD_ARCH/$step" /home/crossbuilder/sku "$@"
done


# Clean up
rm -rf /tmp/build 

if [ "$KEEP_BUILD_ARTIFACTS" == "FALSE" ]
then

apt-get clean 

if  [ -n "$PACKAGES_TO_REMOVE" ]
then
apt-get remove -y $PACKAGES_TO_REMOVE
fi

apt-get autoremove -y 

rm -rf /var/lib/apt/lists/*

fi






