#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

set -e
TARGET_DIR="$(echo $1 | sed -r  's|/$\s*||')"
if [ ! -d "$TARGET_DIR" -o -z "$TARGET_DIR" ]
then
 >&2 echo "Non-existent input dir, usage $0 <TARGET dir> [..args]"
 exit 1
fi

shift 1
set -a
. "$TARGET_DIR/target"
if [ -f "$TARGET_DIR/target.extra" ]
then 
 . "$TARGET_DIR/target.extra"
fi
set +a

if [ -d "$TARGET_DIR/patch" ]
then 
PATCH_DIR="--patchdir='$TARGET_DIR/patch'"
fi

python3 "$(dirname $0)/gen_vars.py" --targetdir="$TARGET_DIR" $PATCH_DIR "$@"

