#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT
usage() {
    echo "Usage: $0 <TARGET_ARCH> <TARGET_DIR>"
    exit 1
}

calculate_hash() {
    local dir="$1"
    local hash=$(tar -C "$dir" -cf - --sort=name --mtime='UTC 2019-01-01' --group=0 --owner=0 --numeric-owner . | sha256sum | awk '{print $1}')
    echo "$hash"
}

if [ -z "$1" ] || [ -z "$2" ] || [ ! -d "$2" ]; then
    usage
fi

ROOT_DIR="$(dirname $0)"

HASH_SCRIPTS=$(calculate_hash "$ROOT_DIR/build_steps_cross")
HASH_TARGET=$(calculate_hash "$2")
HASH_TOP=$(sha256sum "$ROOT_DIR/build_cross_tools" | awk '{print $1}')
HASH_VARS=$("$ROOT_DIR/gen_vars" "$2" | grep -v '#ignore-hash' | sha256sum | awk '{print $1}')

echo "HASH_SCRIPTS: $HASH_SCRIPTS" >&2
echo "HASH_TARGET: $HASH_TARGET" >&2
echo "HASH_TOP: $HASH_TOP" >&2
echo "HASH_VARS: $HASH_VARS" >&2

COMBINED_HASH=$(echo "$HASH_SCRIPTS$HASH_TOP$HASH_TARGET$HASH_VARS" | sha256sum | awk '{print $1}')

echo "$COMBINED_HASH"
