#!/bin/bash
set -x
# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Debootstrap buildroot"
source "$(dirname $0)/../build_common"

set -o pipefail
mkdir -p /var/chroot/
mkdir -p /usr/share/keyrings
rm -rf /var/chroot/buildroot
wget -qO- ${DEBOOTSTRAP_SOURCE}/raspbian.public.key | gpg --dearmor -o /usr/share/keyrings/raspbian-archive-keyring.gpg
debootstrap --arch=${RPI_APT_ARCH} --keyring=/usr/share/keyrings/raspbian-archive-keyring.gpg --verbose --foreign --variant=buildd ${DEBOOTSTRAP_TARGET} /var/chroot/buildroot ${DEBOOTSTRAP_SOURCE}/raspbian/
chroot /var/chroot/buildroot /debootstrap/debootstrap --second-stage
