#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

set -x
STEP_DESCRIPTION="Setup schroot"
source "$(dirname $0)/../build_common"


#FIXME: parametrize nameserver addition
echo "nameserver 8.8.8.8" >> /var/chroot/buildroot/etc/resolv.conf
#FIXME: parametrize rpi archive URL and public key below
echo "deb http://archive.raspberrypi.org/debian $DEBOOTSTRAP_TARGET main" > /var/chroot/buildroot/etc/apt/sources.list.d/raspi.list
chroot /var/chroot/buildroot apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 82B129927FA3303E

#FIXME: we should be also using $DEBOOTSTRAP_TARGET instead of stable!!!
echo "deb http://aptrepo.effective-range.com stable main" > /var/chroot/buildroot/etc/apt/sources.list.d/er.list
chroot /var/chroot/buildroot apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv C1AEE2EDBAEC37595801DDFAE15BC62117A4E0F3

# Install necessary packages
chroot  /var/chroot/buildroot apt update
chroot  /var/chroot/buildroot apt install -y build-essential pkg-config nano wget python3 python3-pip python3-dev raspberrypi-kernel-headers
# Create schroot profile
cat > /etc/schroot/chroot.d/buildroot  << EOF
[buildroot]
description=ER buildroot for uniform builds ($RPI_APT_ARCH)
directory=/var/chroot/buildroot
root-users=root,crossbuilder
users=root,crossbuilder
type=directory
EOF