#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

set -x
STEP_DESCRIPTION="Setup schroot"
source "$(dirname $0)/../build_common"

# Install necessary packages
echo "nameserver 8.8.8.8" >> /var/chroot/buildroot/etc/resolv.conf
chroot  /var/chroot/buildroot apt update
chroot  /var/chroot/buildroot apt install -y build-essential pkg-config nano wget python3 python3-pip python3-dev
# Create schroot profile
cat > /etc/schroot/chroot.d/buildroot  << EOF
[buildroot]
description=ER buildroot for uniform builds ($RPI_APT_ARCH)
directory=/var/chroot/buildroot
root-users=root,crossbuilder
users=root,crossbuilder
type=directory
EOF