#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Install build utils into schroot"
source "$(dirname $0)/../build_common"

# Install necessary packages
echo "nameserver 8.8.8.8" >> /var/chroot/buildroot/etc/resolv.conf

chroot /var/chroot/buildroot apt update

# Fix blocking netbase install
chroot /var/chroot/buildroot apt install -y --no-install-recommends -o Dpkg::Options::="--force-confnew" netbase

# NOTE: this cmake install version will differ from the host cmake version
# compiling cmake from source is possible, but takes 30 minutes, in case there's an error about this
# then this compilation will need to take place as part of the devc build
# Install base packages
chroot /var/chroot/buildroot apt install -y --no-install-recommends cmake ninja-build git debhelper devscripts equivs dbus

# Install packages for python development
chroot /var/chroot/buildroot apt install -y --no-install-recommends python3 python3-pip python3-dev python3-virtualenv dh-virtualenv

# Install library dev packages
chroot /var/chroot/buildroot apt install -y --no-install-recommends libsystemd-dev libdbus-glib-1-dev libgirepository1.0-dev libcairo2-dev

# Install python build packages
# NOTE: https://github.com/scikit-build/ninja-python-distributions/issues/226 latest ninja fails to build
chroot /var/chroot/buildroot pip3 install wheel ninja==1.10.2.3 patchelf meson
