#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

STEP_DESCRIPTION="Install build utils into schroot"
source "$(dirname $0)/../build_common"

chroot /var/chroot/buildroot apt update

# Fix blocking netbase install
chroot /var/chroot/buildroot apt install -y --no-install-recommends -o Dpkg::Options::="--force-confnew" netbase

# NOTE: this cmake install version will differ from the host cmake version
# compiling cmake from source is possible, but takes 30 minutes, in case there's an error about this
# then this compilation will need to take place as part of the devc build
# Install base packages
chroot /var/chroot/buildroot apt install -y --no-install-recommends cmake ninja-build git debhelper devscripts equivs dbus

# Install packages for python development
chroot /var/chroot/buildroot apt install -y --no-install-recommends python3 python3-pip python3-dev python3-virtualenv dh-virtualenv dh-python python3-all

chroot /var/chroot/buildroot pip install stdeb

# Install library dev packages
chroot /var/chroot/buildroot apt install -y --no-install-recommends libsystemd-dev libdbus-glib-1-dev libgirepository1.0-dev libcairo2-dev

# Install python build packages
chroot /var/chroot/buildroot pip3 install wheel ninja patchelf meson
