#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

set -x
STEP_DESCRIPTION="Setup Effective Range APT repository"
source "$(dirname $0)/../build_common"

# add backports to sources.list
echo "deb http://deb.debian.org/debian $DEBOOTSTRAP_TARGET-backports main" > /etc/apt/sources.list.d/backports.list


# Setup in host container
echo "deb http://aptrepo.effective-range.com $DEBOOTSTRAP_TARGET main" > /etc/apt/sources.list.d/er.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv C1AEE2EDBAEC37595801DDFAE15BC62117A4E0F3

# Setup in chroot as well
if [ -d /var/chroot/buildroot ]
then
  echo "deb http://aptrepo.effective-range.com $DEBOOTSTRAP_TARGET main" > /var/chroot/buildroot/etc/apt/sources.list.d/er.list
  chroot /var/chroot/buildroot apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv C1AEE2EDBAEC37595801DDFAE15BC62117A4E0F3
  echo "deb http://deb.debian.org/debian $DEBOOTSTRAP_TARGET-backports main" > /var/chroot/buildroot/etc/apt/sources.list.d/backports.list
fi