#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

set -x
STEP_DESCRIPTION="Setup Effective Range APT repository"
source "$(dirname $0)/../build_common"


#FIXME: we should be also using $DEBOOTSTRAP_TARGET instead of stable!!!
echo "deb http://aptrepo.effective-range.com stable main" > /etc/apt/sources.list.d/er.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv C1AEE2EDBAEC37595801DDFAE15BC62117A4E0F3