#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

set -x
STEP_DESCRIPTION="Setup Effective Range APT repository"
source "$(dirname $0)/../build_common"

# add backports to sources.list
echo <<EOF > /etc/apt/sources.list.d/backports.sources 
Types: deb
URIs: http://deb.debian.org/debian/
Suites: $DEBOOTSTRAP_TARGET-backports
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.pgp
EOF

# Setup in host container
echo <<EOF > /etc/apt/sources.list.d/er.sources 
Types: deb
URIs: http://aptrepo.effective-range.com
Suites: $DEBOOTSTRAP_TARGET
Components: main
Signed-By: /usr/share/keyrings/er-keyring.pgp
EOF

curl -fsSL http://aptrepo.effective-range.com/effectiverange.gpg.key |  tee /usr/share/keyrings/er-keyring.pgp > /dev/null


apt update
# Setup in chroot as well
if [ -d /var/chroot/buildroot ]
then

  echo <<EOF > /var/chroot/buildroot/etc/apt/sources.list.d/er.sources
Types: deb
URIs: http://aptrepo.effective-range.com
Suites: $DEBOOTSTRAP_TARGET
Components: main
Signed-By: /usr/share/keyrings/er-keyring.pgp
EOF

  echo <<EOF > /var/chroot/buildroot/etc/apt/sources.list.d/backports.sources
Types: deb
URIs: http://deb.debian.org/debian/
Suites: $DEBOOTSTRAP_TARGET-backports
Components: main
Signed-By: /usr/share/keyrings/debian-archive-keyring.pgp
EOF

  curl -fsSL http://aptrepo.effective-range.com/effectiverange.gpg.key |  tee /var/chroot/buildroot/usr/share/keyrings/er-keyring.pgp > /dev/null

  chroot /var/chroot/buildroot apt update
fi
