#!/bin/bash

# SPDX-FileCopyrightText: 2024 Ferenc Nandor Janky <ferenj@effective-range.com>
# SPDX-FileCopyrightText: 2024 Attila Gombos <attila.gombos@effective-range.com>
# SPDX-License-Identifier: MIT

set -e

STEP_DESCRIPTION="Installing python build dependecies"
source "$(dirname $0)/../build_common"

apt install -y --no-install-recommends python3-flake8 python3-mypy python3-coverage python3-pytest 

pipx install --global gcovr
pipx install --global markdownify