name: CI

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

jobs:
  test:
    runs-on: ubuntu-22.04
    
    strategy:
        matrix:
          architecture: ["armhf", "amd64", "arm64"]
          distro: ["bullseye", "bookworm"]
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9' 
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Run CI tests
        run: ${{github.workspace}}/test.sh ${{ matrix.architecture }} ${{ matrix.distro }}
